### PR TITLE
ensurePublic can now be passed as an option

### PR DESCRIPTION
**Pull request by benjaminparnell**
This option is then passed to the section extrapolator.

### CODE REVIEW

**Comment by bengourley** [comment]
does this work? Surely you need `opts.ensurePublic == false` which would not get passed down.

**Comment by benjaminparnell** [comment]
Ah yes sorry my bad, I will update

**Comment by benjaminparnell** [comment]
@bengourley fixed in 7ff12ae63d32f33ae8c56c338b245b34ba9bf7b2. Tested by `npm link`ing this into cf-dedupe-list-aggregator and then linking that into Perks

**Comment by serby** [comment]
@benjaminparnell I'm not keen on the name of `ensurePublic` as it only ensures that the section is public. Non-public articles will never get included even when false. I have no problem with the functionality it just should have been called something more like `publicSectionsItemsOnly`

**Pull request merged**
